import os, sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))


from io import BytesIO
from docxtpl import DocxTemplate, RichText
from azure.storage.blob import BlobServiceClient

from config.settings import (
    AZURE_BLOB_CONN_STRING,
    BLOB_CONTAINER,
    INDEX_PREFIX,
)

TEMPLATE_NAME = "CSR.docx"
OUTPUT_NAME = "CSR_filled.docx"



import re
from docxtpl import RichText

def markdown_to_richtext(text: str) -> RichText:
    """
    Converts **bold** markdown to DOCX bold runs.
    """
    rt = RichText()
    pattern = re.compile(r"\*\*(.*?)\*\*")

    last_idx = 0
    for match in pattern.finditer(text):
        start, end = match.span()

        # Normal text before bold
        if start > last_idx:
            rt.add(text[last_idx:start])

        # Bold text
        rt.add(match.group(1), bold=True)

        last_idx = end

    # Remaining text
    if last_idx < len(text):
        rt.add(text[last_idx:])

    return rt


def normalize_prefix(prefix: str) -> str:
    """
    Ensures no trailing slash
    """
    return prefix.rstrip("/")


def render_docx(llm_text: str):
    prefix = normalize_prefix(INDEX_PREFIX)

    # 1️⃣ Connect to Blob Storage
    blob_service = BlobServiceClient.from_connection_string(
        AZURE_BLOB_CONN_STRING
    )
    container = blob_service.get_container_client(BLOB_CONTAINER)

    # 2️⃣ Download template into RAM
    template_blob_path = f"{prefix}/{TEMPLATE_NAME}"
    print("Downloading template:", template_blob_path)

    template_blob = container.get_blob_client(template_blob_path)

    if not template_blob.exists():
        raise FileNotFoundError(
            f"Template not found in blob storage: {template_blob_path}"
        )

    template_bytes = template_blob.download_blob().readall()
    template_stream = BytesIO(template_bytes)

    # 3️⃣ Render DOCX in memory
    doc = DocxTemplate(template_stream)

    def to_rich_text(text: str) -> RichText:
        return RichText(text)

    context = {
        "inclusion_criteria": markdown_to_richtext(to_rich_text(llm_text))
    }

    doc.render(context)

    # 4️⃣ Save rendered DOCX to RAM
    output_stream = BytesIO()
    doc.save(output_stream)
    output_stream.seek(0)

    # 5️⃣ Upload rendered DOCX back to Blob
    output_blob_path = f"{prefix}/{OUTPUT_NAME}"
    print("Uploading rendered file:", output_blob_path)

    output_blob = container.get_blob_client(output_blob_path)
    output_blob.upload_blob(output_stream, overwrite=True)

    print(f"☁️ CRS rendered & uploaded → {output_blob_path}")


# -------------------------
# ENTRY
# -------------------------
if __name__ == "__main__":
    render_docx(
        RichText("This inclusion criterion was generated by the LLM and injected into CRS<10.")
    )